### ISSUE TITLE
Better ways to get page URL in README.md example

### ISSUE THREAD

**Issue by amankkg** [syntra/gatsby-remark-social-cards#10]
Since every page component receives router's `location` in `props` one can use this information to construct the final URL.

First, in post template component we pass it to `Layout`:
```jsx
export default ({ location }) => {
  return <Layout pathname={location.pathname}>{/* ... */}</Layout>;
};
```
Then use it instead of `slug`:
```jsx
const Layout = ({ pathname, children }) => (
  <StaticQuery
    query={graphql`
      query SiteTitleQuery {
        site {
          siteMetadata {
            title
            siteUrl
          }
        }
      }
    `}
    render={data => (
      <Helmet title={data.site.siteMetadata.title}>
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:image"
          content={`${data.site.siteMetadata.siteUrl}${pathname}twitter-card.jpg`}
        />
      </Helmet>
      { /* ... */ }
    )}
  />
);
```

[Here](https://github.com/amankkg/amank.me/blob/e8ac444c83ce61309fc82456172a1998b020cd9d/src/md-template.js#L28-L29) is how I do this. I get `siteUrl` using `graphql` and `location.pathname` from `props`.

Also, this way we don't have to care about how markdown page URLs are being constructed, e.g. `${siteUrl}/${slug}` or `${siteUrl}/blog/{$slug}` etc.

I believe this would be more straightforward for people.

**Comment by ariamckinley** [comment]
Thanks for that :trophy:! If you (or anyone reading this) would be willing to put together a pull request I'll merge it right away. I won't be able to add this myself for another week or two since I'm out of town.

**Comment by amankkg** [comment]
Cool! I can take care of it then.

**Comment by AhsanAyaz** [comment]
@garetmckinley can you please review the PR above and merge it?
Thanks :)

**Comment by ariamckinley** [comment]
@AhsanAyaz done. Sorry for the delay everyone, was a bit behind on a lot of things and must have missed the PR notification.

**Comment by AhsanAyaz** [comment]
@garetmckinley, no worries. You're doing great stuff! Thanks 🎉
