### ISSUE TITLE
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by necrojan** [syntra/gatsby-remark-social-cards#23]
Hi, Thank you for this awesome plugin. 
I created my site using stackbit so I can have it up and running quickly. 
I've tried to use this plugin and Ive followed the instructions in the installation. But right after I 
step no. 2 and I run the site `npm run develop` I immediately encounter this error

> Plugin gatsby-remark-page-creator returned an error The "path" argument must be of type string. Received type undefined Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be type string. Received type undefined

I am new to gatsby so I am not sure how to fix the error.

Thank you.

**Comment by ariamckinley** [comment]
Hello @necrojan, welcome to the world of gatsby :)

What OS are you on and what version of gatsby are you using?

**Comment by necrojan** [comment]
Thank you for your response and welcome @garetmckinley 
I've finally manged to sort it on my own :) 
I'll close this now

**Comment by rohit-gohri** [comment]
> Thank you for your response and welcome @garetmckinley
> I've finally manged to sort it on my own :)
> I'll close this now

Could you tell how you fixed it? I'm receiving the same error

**Comment by rohit-gohri** [comment]
Figured it out, needed to add logic to create slugs for pages in gatsby-node.js. 
https://www.gatsbyjs.org/docs/creating-slugs-for-pages/
